name: flutter_demo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # https://github.com/flutterchina/dio
  dio: ^2.1.10

  # https://pub.dev/packages/event_bus
  event_bus: ^1.0.1

  # https://pub.dev/packages/flutter_progress_hud
  flutter_progress_hud: ^1.0.1

  # https://pub.dev/packages/synchronized
  synchronized: ^2.1.0+1

  #
  # 插件
  #
  
  # https://pub.dev/packages/image_crop
  image_crop: ^0.3.1

  # https://pub.dev/packages/image_picker
  image_picker: ^0.6.1+4

  # https://pub.dev/packages/device_info
  device_info: ^0.3.0

  # webview_flutter
  webview_flutter: ^0.3.3+1
  
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.0.3
  
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/locale/i18n_zh.json
    - assets/locale/i18n_en.json

    - assets/image/1.jpg
    - assets/image/2.jpg
    - assets/image/3.jpg
    - assets/image/4.jpg
    - assets/image/5.jpg
    - assets/image/6.jpg
    - assets/image/7.jpg

    - assets/avatar/1.jpg
    - assets/avatar/2.jpg
    - assets/avatar/3.jpg
    - assets/avatar/4.jpg
    - assets/avatar/4.jpg
    - assets/avatar/4.jpg
    - assets/avatar/4.jpg
    - assets/avatar/4.jpg
    - assets/avatar/4.jpg
    - assets/avatar/4.jpg
    - assets/avatar/4.jpg
    - assets/avatar/4.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
